### ISSUE TITLE
Hard-coded X Axis

### ISSUE THREAD

**Issue by chopj** [dima117/Chart.AltLineChart#20]
Is it possible to hard-code an X-axis?  I have a set of data from a year, but its sparse and not evenly distributed (for example, two datapoints from random days in Jan, five points in March, none in May, etc).  Is it possible to hard-code the scale, so I have a nice Jan-Dec scale, despite not having data in that range.

**Comment by dima117** [comment]
Hi

I'm sorry for very late reply. You can manually set scale values using the 'scaleOverride', 'scaleStartValue', 'scaleSteps' and 'scaleStepWidth' properties. But you can set equally allocated values only. In your case month values aren't equally allocated because all months has different count of days.

**Comment by swaffoja** [comment]
'scaleOverride' seems to override the Y-axis. Is there a way to override the X-axis? For example, I want my x-axis to show a 24-hour time period even if I only have 1 data point. Example:

```
Aug 12, 2:00, 4:00, 6:00, 8:00, 10:00, 12:00, 2:00, 4:00, 6:00, 8:00, 10:00, Aug 13
```

**Comment by jasconius** [comment]
I also would like to override the X-axis... can't find any way of doing so
