### ISSUE TITLE
TypeError: (intermediate value).Scatter is not a function

### ISSUE THREAD

**Issue by AnniekJose** [dima117/Chart.AltLineChart#27]
I grabbed Chart.Scatter.js with bower install, but I can't seem to get it working. 
I keep getting the error: TypeError: (intermediate value).Scatter is not a function.

I wanted to use the date scale function. 

Can anyone help me?

**Comment by dima117** [comment]
I'm sorry for very late reply.
Please give me an example on http://jsfiddle.net or similar site.

**Comment by dima117** [comment]
Hi,

apparently the cause of the problem is an incorrect inclusion of the Chart.Scatter.js or  Chart.js library into your project. Unfortunately, without knowing the details, it is difficult to advise something to you.

If the problem is still relevant, please email me at the email and, if possible, send me a sample that demonstrates the problem.

**Comment by cwingrav** [comment]
I ran into this problem. I switched from a local copy of Chart.Scatter.min.js to a local copy of Chart.Scatter.js and it worked. Odd.
